// <auto-generated />
using System;
using ConsoleApp.DAL.EntityFactory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp.DAL.EntityFactory.Migrations.Sqlite
{
    [DbContext(typeof(EntityContextSqlite))]
    partial class EntityContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("ConsoleApp.Abstractions.DataObjects.Blog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("ConsoleApp.Abstractions.DataObjects.BlogImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdBlog")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.HasKey("id");

                    b.HasIndex("IdBlog")
                        .IsUnique();

                    b.ToTable("BlogImages");
                });

            modelBuilder.Entity("ConsoleApp.Abstractions.DataObjects.ObjectTest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("str_value")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("ObjectTests");
                });

            modelBuilder.Entity("ConsoleApp.Abstractions.DataObjects.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdBlog")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("IdBlog");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ConsoleApp.Abstractions.DataObjects.BlogImage", b =>
                {
                    b.HasOne("ConsoleApp.Abstractions.DataObjects.Blog", "Blog")
                        .WithOne("BlogImage")
                        .HasForeignKey("ConsoleApp.Abstractions.DataObjects.BlogImage", "IdBlog")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("ConsoleApp.Abstractions.DataObjects.Post", b =>
                {
                    b.HasOne("ConsoleApp.Abstractions.DataObjects.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("IdBlog")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("ConsoleApp.Abstractions.DataObjects.Blog", b =>
                {
                    b.Navigation("BlogImage");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
